# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-14 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaproszenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc', models.CharField(max_length=300)),
                ('czas_wiadomosci', models.DateTimeField(auto_now_add=True)),
                ('do_usera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaproszenie_odebrane', to=settings.AUTH_USER_MODEL)),
                ('od_usera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaproszenie_wyslane', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
