# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-15 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaproszenie',
            name='do_usera',
            field=models.ForeignKey(help_text='Wybierz Użytkownika z którym chcesz rozegrać grę.', on_delete=django.db.models.deletion.CASCADE, related_name='zaproszenie_odebrane', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik do zaproszenia'),
        ),
        migrations.AlterField(
            model_name='zaproszenie',
            name='wiadomosc',
            field=models.CharField(blank=True, help_text='Zawsze dobrze powiedzieć coś miłego ;)', max_length=300, verbose_name='Opcjonalna wiadomość'),
        ),
    ]
